### PR TITLE
Don't call onRender if the window is minimized it will crash.

### PR DESCRIPTION
**Pull request by RanXacT**
Adds a window callback for "shouldRender" and respect it. On windows this
translates to IsIconic().

### CODE REVIEW

**Comment by RanXacT** [comment]
Feel free to resolve another way, To reproduce the crash, just minimize the window.

**Comment by kecho** [comment]
Weird, I dont reproduce the crash locally. I can minimize just fine wondering whats the callstack for the crash.
Merging change as is, possible that it dies with certain drives / versions of windows!

**Comment by RanXacT** [comment]
I get:

**Comment by RanXacT** [comment]
Which is to say, the size of the window reports as 0 when minimized, and that causes an exception.

**Comment by kecho** [comment]
aha! so this is a python exception. I dont hit it because i write this protection on my on_render function, duh. Good solution, thanks a bunch!

If anybody ever needs events on minimization then i guess I could add them. Otherwise this would do.

**Pull request merged**
